/// App-wide constants
class AppConstants {
  // General
  static const String appName = 'AI ECD Screening';
  static const String appVersion = '1.0.0';

  // API Endpoints
  static const String baseUrl = String.fromEnvironment(
    'ECD_API_BASE_URL',
    defaultValue: 'http://127.0.0.1:8000',
  );
  static const String loginEndpoint = '/auth/login';
  static const String registerEndpoint = '/auth/register';
  // OTP / session endpoints (server-driven two-step flow)
  static const String otpInitiateEndpoint = '/auth/otp/initiate';
  static const String otpVerifyEndpoint = '/auth/otp/verify';
  static const String otpResendEndpoint = '/auth/otp/resend';
  static const String sessionExchangeEndpoint = '/auth/session';
  static const String screeningEndpoint = '/screening/submit';
  static const String childRegisterEndpoint = '/children/register';
  static const String childListEndpoint = '/children';
  static const String childDetailEndpoint = '/children';
  static const String referralEndpoint = '/referral/create';

  // Local Storage Keys
  static const String authTokenKey = 'auth_token';
  static const String refreshTokenKey = 'refresh_token';
  static const String userDataKey = 'user_data';
  static const String childrenDataKey = 'children_data';
  static const String screeningsDataKey = 'screenings_data';

  // Hive Box Names
  static const String awwBoxName = 'aww_box';
  static const String childBoxName = 'child_box';
  static const String screeningBoxName = 'screening_box';
  static const String referralBoxName = 'referral_box';
  static const String childSyncBoxName = 'child_sync_box';

  // Domain Constants
  static const List<String> domains = ['GM', 'FM', 'LC', 'COG', 'SE'];
  static const Map<String, String> domainNames = {
    'GM': 'Gross Motor',
    'FM': 'Fine Motor',
    'LC': 'Language & Communication',
    'COG': 'Cognitive',
    'SE': 'Social & Emotional',
  };

  // Andhra Pradesh district -> mandals (from the referenced Wikipedia list).
  static const Map<String, List<String>> apDistrictMandals = {
    'Alluri Sitharama Raju': [
      'Ananthagiri',
      'Araku Valley',
      'Chintapalle',
      'Dumbriguda',
      'G. Madugula',
      'Gudem Kotha Veedhi',
      'Hukumpeta',
      'Koyyuru',
      'Munchingi Puttu',
      'Paderu',
      'Peda Bayalu',
    ],
    'Anakapalli': [
      'Atchutapuram',
      'Elamanchili',
      'Kotauratla',
      'Nakkapalle',
      'Payakaraopeta',
      'Rambilli',
      'Sarvasiddhi Rayavaram',
      'Anakapalle',
      'Butchayyapeta',
      'Cheedikada',
      'Chodavaram',
      'Devarapalli',
      'K.Kotapadu',
      'Kasimkota',
      'Munagapaka',
      'Paravada',
      'Sabbavaram',
      'Golugonda',
      'Madugula',
      'Makavarapalem',
      'Narsipatnam',
      'Nathavaram',
      'Ravikamatham',
      'Rolugunta',
    ],
    'Anantapur': [
      'Anantapur',
      'Atmakur',
      'Bukkaraya Samudram',
      'Garladinne',
      'Kudair',
      'Narpala',
      'Peddapappur',
      'Putlur',
      'Raptadu',
      'Singanamala',
      'Tadipatri',
      'Yellanur',
      'Gooty',
      'Guntakal',
      'Pamidi',
      'Peddavadugur',
      'Uravakonda',
      'Vajrakarur',
      'Vidapanakal',
      'Yadiki',
      'Beluguppa',
      'Bommanahal',
      'Brahmasamudram',
      'D.Hirehal',
      'Gummagatta',
      'Kalyandurg',
      'Kambadur',
      'Kanekal',
      'Kundurpi',
      'Rayadurg',
      'Settur',
    ],
    'Annamayya': [
      'Beerangi Kothakota',
      'Chowdepalle',
      'Kurabalakota',
      'Madanapalle',
      'Mulakalacheruvu',
      'Nimmanapalle',
      'Peddamandyam',
      'Peddathippasamudram',
      'Punganur',
      'Ramasamudram',
      'Thamballapalle',
      'Gurramkonda',
      'Kalakada',
      'Kalikiri',
      'Kambhamvaripalle',
      'Pileru',
      'Sodam',
      'Somala',
      'Vayalpad',
      'Chinnamandyam',
      'Galiveedu',
      'Lakkireddipalli',
      'Ramapuram',
      'Rayachoti',
      'Sambepalli',
    ],
    'Bapatla': [
      'Bapatla',
      'Karlapalem',
      'Martur',
      'Parchur',
      'Pittalavanipalem',
      'Yeddanapudi',
      'Chinaganjam',
      'Chirala',
      'Inkollu',
      'Karamchedu',
      'Vetapalem',
      'Amruthalur',
      'Bhattiprolu',
      'Cherukupalle',
      'Kolluru',
      'Nagaram',
      'Nizampatnam',
      'Repalle',
      'Tsundur',
      'Vemuru',
    ],
    'Chittoor': [
      'Bangarupalem',
      'Chittoor',
      'Chittoor Urban',
      'Gangadhara Nellore',
      'Gudipala',
      'Irala',
      'Penumuru',
      'Pulicherla',
      'Puthalapattu',
      'Rompicherla',
      'Sri Rangaraja Puram',
      'Thavanampalle',
      'Vedurukuppam',
      'Yadamarri',
      'Kuppam',
      'Ramakuppam',
      'Santhipuram',
      'Gudipalle',
      'Nagari',
      'Nindra',
      'Palasamudram',
      'Vijayapuram',
      'Karvetinagar',
      'Baireddipalle',
      'Gangavaram',
      'Palamaner',
      'Peddapanjani',
      'Venkatagirikota',
    ],
    'Dr. B.R. Ambedkar Konaseema': [
      'Allavaram',
      'Amalapuram',
      'I. Polavaram',
      'Katrenikona',
      'Malikipuram',
      'Mamidikuduru',
      'Mummidivaram',
      'Razole',
      'Sakhinetipalle',
      'Uppalaguptam',
      'Ainavilli',
      'Alamuru',
      'Ambajipeta',
      'Atreyapuram',
      'Kothapeta',
      'P. Gannavaram',
      'Ravulapalem',
      'K. Gangavaram',
      'Ramachandrapuram',
    ],
    'East Godavari': [
      'Chagallu',
      'Devarapalle',
      'Gopalapuram',
      'Kovvur',
      'Nallajerla',
      'Nidadavole',
      'Peravali',
      'Tallapudi',
      'Undrajavaram',
      'Anaparthi',
      'Biccavolu',
      'Gokavaram',
      'Kadiam',
      'Kapileswarapuram',
      'Korukonda',
      'Mandapeta',
      'Rajahmundry Urban',
      'Rajahmundry Rural',
      'Rajanagaram',
      'Rangampeta',
      'Rayavaram',
      'Seethanagaram',
    ],
    'Eluru': [
      'Bhimadole',
      'Denduluru',
      'Eluru',
      'Kaikalur',
      'Kalidindi',
      'Mandavalli',
      'Mudinepalle',
      'Nidamarru',
      'Pedapadu',
      'Pedavegi',
      'Unguturu',
      'Buttayagudem',
      'Dwaraka Tirumala',
      'Jangareddygudem',
      'Jeelugu Milli',
      'Kamavarapukota',
      'Koyyalagudem',
      'Kukunoor',
      'Polavaram',
      'T. Narasapuram',
      'Velairpadu',
      'Agiripalli',
      'Chatrai',
      'Chintalapudi',
      'Lingapalem',
      'Musunuru',
      'Nuzvid',
    ],
    'Guntur': [
      'Guntur East',
      'Guntur West',
      'Medikonduru',
      'Pedakakani',
      'Pedanandipadu',
      'Phirangipuram',
      'Prathipadu',
      'Tadikonda',
      'Thullur',
      'Vatticherukuru',
      'Chebrolu',
      'Duggirala',
      'Kakumanu',
      'Kollipara',
      'Mangalagiri',
      'Ponnur',
      'Tadepalle',
      'Tenali',
    ],
    'Kadapa (YSR)': [
      'Atlur',
      'B. Kodur',
      'Badvel',
      'Brahmamgarimattam',
      'Chapad',
      'Duvvur',
      'Gopavaram',
      'Kalasapadu',
      'Khajipet',
      'Porumamilla',
      'S.Mydukur',
      'Sri Avadhutha Kasinayana',
      'Jammalamadugu',
      'Kondapuram',
      'Muddanur',
      'Mylavaram',
      'Peddamudium',
      'Proddatur',
      'Rajupalem',
      'Chennur',
      'Chinthakommadinne',
      'Kadapa',
      'Kamalapuram',
      'Pendlimarri',
      'Sidhout',
      'Vallur',
      'Vontimitta',
      'Yerraguntla',
      'Chakrayapet',
      'Lingala',
      'Pulivendla',
      'Simhadripuram',
      'Thondur',
      'Veerapunayunipalle',
      'Vempalle',
      'Vemula',
      'Nandalur',
      'Rajampet',
      'T. Sundupalle',
      'Veeraballi',
    ],
    'Kakinada': [
      'Gollaprolu',
      'Kajuluru',
      'Kakinada Rural',
      'Kakinada Urban',
      'Karapa',
      'Kothapalle',
      'Pedapudi',
      'Pithapuram',
      'Thallarevu',
      'Gandepalle',
      'Jaggampeta',
      'Kirlampudi',
      'Kotananduru',
      'Peddapuram',
      'Prathipadu',
      'Rowthulapudi',
      'Samalkota',
      'Sankhavaram',
      'Thondangi',
      'Tuni',
      'Yeleswaram',
    ],
    'Kanigiri (Merged/Restructured)': [
      'Chandra Sekhara Puram',
      'Hanumanthuni Padu',
      'Kanigiri',
      'Pamur',
      'Pedacherlo Palle',
      'Veligandla',
    ],
    'Krishna': [
      'Bapulapadu',
      'Gannavaram',
      'Gudivada',
      'Gudlavalleru',
      'Nandivada',
      'Pedaparupudi',
      'Unguturu',
      'Avanigadda',
      'Bantumilli',
      'Challapalli',
      'Ghantasala',
      'Guduru',
      'Koduru',
      'Kruthivennu',
      'Machilipatnam',
      'Mopidevi',
      'Nagayalanka',
      'Pedana',
      'Kankipadu',
      'Movva',
      'Pamarru',
      'Pamidimukkala',
      'Penamaluru',
      'Thotlavalluru',
      'Vuyyuru',
    ],
    'Kurnool': [
      'Adoni Urban',
      'Adoni Rural',
      'Gonegandla',
      'Holagunda',
      'Kosigi',
      'Kowthalam',
      'Mantralayam',
      'Nandavaram',
      'Pedda Kadubur',
      'Yemmiganur',
      'C.Belagal',
      'Gudur',
      'Kallur',
      'Kodumur',
      'Kurnool Urban',
      'Kurnool Rural',
      'Orvakal',
      'Veldurthi',
      'Alur',
      'Aspari',
      'Chippagiri',
      'Devanakonda',
      'Halaharvi',
      'Krishnagiri',
      'Maddikera East',
      'Pattikonda',
      'Tuggali',
    ],
    'Madanapalle (New)': [
      'Beerangi Kothakota',
      'Chowdepalle',
      'Kurabalakota',
      'Madanapalle',
      'Mulakalacheruvu',
      'Nimmanapalle',
      'Peddamandyam',
      'Peddathippasamudram',
      'Punganur',
      'Ramasamudram',
      'Thamballapalle',
    ],
    'Markapuram (New)': [
      'Chandra Sekhara Puram',
      'Hanumanthuni Padu',
      'Kanigiri',
      'Pamur',
      'Pedacherlo Palle',
      'Veligandla',
      'Ardhaveedu',
      'Bestawaripeta',
      'Cumbum',
      'Dornala',
      'Giddalur',
      'Konakanamitla',
      'Komarolu',
      'Markapuram',
      'Peda Araveedu',
      'Pullalacheruvu',
      'Podili',
      'Racherla',
      'Tarlupadu',
      'Tripuranthakam',
      'Yerragondapalem',
    ],
    'Nandyal': [
      'Atmakur',
      'Bandi Atmakur',
      'Jupadu Bungalow',
      'Kothapalle',
      'Midthuru',
      'Nandikotkur',
      'Pagidyala',
      'Pamulapadu',
      'Srisailam',
      'Velgodu',
      'Banaganapalle',
      'Koilkuntla',
      'Kolimigundla',
      'Owk',
      'Sanjamala',
      'Bethamcherla',
      'Dhone',
      'Peapally',
      'Allagadda',
      'Chagalamarri',
      'Dornipadu',
      'Gadivemula',
      'Gospadu',
      'Mahanandi',
      'Nandyal Rural',
      'Nandyal Urban',
      'Panyam',
      'Rudravaram',
      'Uyyalawada',
    ],
    'Nellore (SPSR)': [
      'Ananthasagaram',
      'Anumasamudrampeta',
      'Atmakur',
      'Chejerla',
      'Kaluvoya',
      'Marripadu',
      'Sangam',
      'Sitarampuramu',
      'Udayagiri',
      'Gudur',
      'Chillakur',
      'Kota',
      'Allur',
      'Bogolu',
      'Dagadarthi',
      'Duttaluru',
      'Jaladanki',
      'Kaligiri',
      'Kavali',
      'Kodavaluru',
      'Vidavaluru',
      'Vinjamuru',
      'Buchireddypalem',
      'Indukurpet',
      'Kovur',
      'Manubolu',
      'Muttukuru',
      'Nellore Urban',
      'Nellore Rural',
      'Podalakuru',
      'Rapuru',
      'Saidapuramu',
      'Thotapalligudur',
      'Venkatachalam',
    ],
    'NTR': [
      'Chandarlapadu',
      'Jaggayyapeta',
      'Kanchikacherla',
      'Nandigama',
      'Penuganchiprolu',
      'Vatsavai',
      'Veerullapadu',
      'A. Konduru',
      'Gampalagudem',
      'Reddigudem',
      'Tiruvuru',
      'Vissannapeta',
      'G.Konduru',
      'Ibrahimpatnam',
      'Mylavaram',
      'Vijayawada Rural',
      'Vijayawada North',
      'Vijayawada Central',
      'Vijayawada East',
      'Vijayawada West',
    ],
    'Palnadu': [
      'Dachepalle',
      'Durgi',
      'Gurazala',
      'Karempudi',
      'Macherla',
      'Machavaram',
      'Piduguralla',
      'Rentachintala',
      'Veldurthi',
      'Bollapalle',
      'Chilakaluripet',
      'Edlapadu',
      'Ipuru',
      'Nadendla',
      'Narasaraopet',
      'Nuzendla',
      'Rompicherla',
      'Savalyapuram',
      'Vinukonda',
      'Amaravathi',
      'Atchampet',
      'Bellamkonda',
      'Krosuru',
      'Muppalla',
      'Nekarikallu',
      'Pedakurapadu',
      'Rajupalem',
      'Sattenapalle',
    ],
    'Parvathipuram Manyam': [
      'Bhamini',
      'Gummalakshmipuram',
      'Jiyyammavalasa',
      'Kurupam',
      'Palakonda',
      'Seethampeta',
      'Veeraghattam',
      'Balijipeta',
      'Garugubilli',
      'Komarada',
      'Makkuva',
      'Pachipenta',
      'Parvathipuram',
      'Salur',
      'Seethanagaram',
    ],
    'Polavaram (New)': [
      'Chintur',
      'Etapaka',
      'Kunavaram',
      'Vararamachandrapuram',
      'Addateegala',
      'Devipatnam',
      'Gangavaram',
      'Gurthedu',
      'Maredumilli',
      'Rajavommangi',
      'Rampachodavaram',
      'Y. Ramavaram',
    ],
    'Prakasam': [
      'Korisapadu',
      'J. Panguluru',
      'Addanki',
      'Ballikurava',
      'Santhamaguluru',
      'Mundlamuru Ongole',
      'Thallur',
      'Darsi',
      'Donakonda Kanigiri',
      'Kurichedu',
      'Gudluru',
      'Kandukuru',
      'Lingasamudram',
      'Ulavapadu',
      'Marripudi',
      'Ponnaluru',
      'Voletivaripalem',
      'Chimakurthi',
      'Kondapi',
      'Kotha Patnam',
      'Maddipadu',
      'Naguluppalapadu',
      'Ongole Urban',
      'Ongole Rural',
      'Santhanuthala Padu',
      'Singarayakonda',
      'Tangutur',
      'Zarugumilli',
    ],
    'Sri Sathya Sai': [
      'Bathalapalle',
      'Chennekothapalle',
      'Dharmavaram',
      'Kanaganapalle',
      'Mudigubba',
      'Ramagiri',
      'Tadimarri',
      'Gandlapenta',
      'Kadiri',
      'Lepakshi',
      'Nallacheruvu',
      'Nambulapulakunta',
      'Tanakal',
      'Agali',
      'Amarapuram',
      'Gudibanda',
      'Madakasira',
      'Rolla',
      'Chilamathur',
      'Gorantla',
      'Hindupur',
      'Parigi',
      'Penukonda',
      'Roddam',
      'Somandepalle',
      'Talupula',
      'Amadagur',
      'Bukkapatnam',
      'Kothacheruvu',
      'Nallamada',
      'Obuladevaracheruvu',
      'Puttaparthi',
    ],
    'Srikakulam': [
      'Ichchapuram',
      'Kanchili',
      'Kaviti',
      'Mandasa',
      'Palasa',
      'Sompeta',
      'Vajrapukothuru',
      'Amadalavalasa',
      'Burja',
      'Etcherla',
      'Ganguvarisigadam',
      'Gara',
      'Jalumuru',
      'Laveru',
      'Narasannapeta',
      'Polaki',
      'Ponduru',
      'Ranastalam',
      'Sarubujjili',
      'Srikakulam',
      'Hiramandalam',
      'Kotabommali',
      'Kothuru',
      'Lakshminarsupeta',
      'Meliaputti',
      'Nandigam',
      'Pathapatnam',
      'Santhabommali',
      'Saravakota',
      'Tekkali',
    ],
    'Tirupati': [
      'Balayapalli',
      'Dakkili',
      'K. V. B. Puram',
      'Nagalapuram',
      'Narayanavanam',
      'Pichatur',
      'Renigunta',
      'Srikalahasti',
      'Thottambedu',
      'Venkatagiri',
      'Yerpedu',
      'Buchinaidu Kandriga',
      'Chittamur',
      'Doravarisatram',
      'Naidupeta',
      'Ojili',
      'Pellakuru',
      'Satyavedu',
      'Sullurpeta',
      'Tada',
      'Vakadu',
      'Varadaiahpalem',
      'Chandragiri',
      'Chinnagottigallu',
      'Chitvel',
      'Kodur',
      'Obulavaripalle',
      'Pakala',
      'Penagalur',
      'Pullampeta',
      'Puttur',
      'Ramachandrapuram',
      'Tirupati Rural',
      'Tirupati Urban',
      'Vadamalapeta',
      'Yerravaripalem',
    ],
    'Visakhapatnam': [
      'Anandapuram',
      'Bheemunipatnam',
      'Padmanabham',
      'Seethammadhara',
      'Visakhapatnam Rural',
      'Gajuwaka',
      'Gopalapatnam',
      'Maharanipeta',
      'Mulagada',
      'Pedagantyada',
      'Pendurthi',
    ],
    'Vizianagaram': [
      'Badangi',
      'Bobbili',
      'Dattirajeru',
      'Gajapathinagaram',
      'Mentada',
      'Ramabhadrapuram',
      'Therlam',
      'Cheepurupalle',
      'Garividi',
      'Gurla',
      'Merakamudidam',
      'Rajam',
      'Regidi Amadalavalasa',
      'Santhakaviti',
      'Vangara',
      'Bhogapuram',
      'Bondapalle',
      'Denkada',
      'Gantyada',
      'Jami',
      'Kothavalasa',
      'Lakkavarapukota',
      'Nellimarla',
      'Pusapatirega',
      'Srungavarapukota',
      'Vepada',
      'Vizianagaram',
    ],
    'West Godavari': [
      'Akividu',
      'Bhimavaram',
      'Kalla',
      'Palacoderu',
      'Undi',
      'Veeravasaram',
      'Achanta',
      'Mogalthur',
      'Palakollu',
      'Penugonda',
      'Penumantra',
      'Poduru',
      'Yelamanchili',
      'Attili',
      'Ganapavaram',
      'Iragavaram',
      'Pentapadu',
      'Tadepalligudem',
      'Tanuku',
    ],
  };

  // Age Groups
  static const Map<String, String> ageGroups = {
    '0-6m': '0-6 Months',
    '6-12m': '6-12 Months',
    '12-18m': '12-18 Months',
    '18-24m': '18-24 Months',
    '24-36m': '24-36 Months',
    '36-48m': '36-48 Months',
    '48-60m': '48-60 Months',
    '60-72m': '60-72 Months',
  };

  // Risk Levels
  static const Map<String, String> riskLevels = {
    'low': 'Low Risk',
    'medium': 'Medium Risk',
    'high': 'High Risk',
    'critical': 'Critical Risk',
  };

  // Timeouts
  static const Duration apiTimeout = Duration(seconds: 30);
  static const Duration sessionTimeout = Duration(hours: 1);

  // Validation
  static const int minPasswordLength = 6;
  static const int maxNameLength = 50;
  static const String phoneRegex = r'^[0-9]{10}$';

  // DPDP Act Compliance
  static const String dataUsageDisclaimer = '''
This app uses child development data for screening purposes only.
Your data will be securely stored and used only for:
- Early identification of developmental risks
- Providing personalized intervention recommendations
- Government health program monitoring

This is NOT diagnosis. All results are for decision-support only.
Data will be protected under the Digital Personal Data Protection Act, 2023.
  ''';

  // AWC Code to District and Mandal Mapping
  static const Map<String, Map<String, String>> awcCodeMappings = {
    'AWW_DEMO_0001': {'district': 'Visakhapatnam', 'mandal': 'Visakhapatnam'},
    'AWW_DEMO_001': {'district': 'Visakhapatnam', 'mandal': 'Visakhapatnam'},
    'AWW_DEMO_002': {'district': 'Visakhapatnam', 'mandal': 'Anakapalle'},
    'AWW_DEMO_003': {'district': 'Krishna', 'mandal': 'Vijayawada'},
    'AWW_DEMO_004': {'district': 'Krishna', 'mandal': 'Machilipatnam'},
    'AWW_DEMO_005': {'district': 'Guntur', 'mandal': 'Guntur'},
    'AWS_DEMO_0001': {'district': 'Visakhapatnam', 'mandal': 'Visakhapatnam'},
    'AWS_DEMO_001': {'district': 'Visakhapatnam', 'mandal': 'Visakhapatnam'},
    'AWS_DEMO_002': {'district': 'Visakhapatnam', 'mandal': 'Anakapalle'},
    'AWS_DEMO_003': {'district': 'Krishna', 'mandal': 'Vijayawada'},
  };

  /// Get district and mandal for an AWC code
  static Map<String, String> getAwcMapping(String awcCode) {
    final normalized = awcCode.trim().toUpperCase();
    return awcCodeMappings[normalized] ?? {'district': '', 'mandal': ''};
  }
}
