class NeuroQuestion {
  final String text;
  final int weight;

  const NeuroQuestion({
    required this.text,
    required this.weight,
  });
}

class NeuroQuestionSet {
  final List<NeuroQuestion> autism;
  final List<NeuroQuestion> adhd;
  final List<NeuroQuestion> behavior;

  const NeuroQuestionSet({
    required this.autism,
    required this.adhd,
    required this.behavior,
  });
}

class _Band {
  final int min;
  final int max;
  final NeuroQuestionSet set;

  const _Band(this.min, this.max, this.set);

  bool contains(int ageMonths) => ageMonths >= min && ageMonths <= max;
}

class NeuroBehavioralQuestionBank {
  static NeuroQuestionSet forAgeMonths(int ageMonths) {
    for (final band in _bands) {
      if (band.contains(ageMonths)) return band.set;
    }
    return _bands.last.set;
  }

  static NeuroQuestion q(String text, [int weight = 4]) =>
      NeuroQuestion(text: text, weight: weight);

  static NeuroQuestionSet _set({
    required List<NeuroQuestion> aut,
    required List<NeuroQuestion> adhd,
    required List<NeuroQuestion> beh,
  }) {
    if (aut.length != 15 || adhd.length != 15 || beh.length != 15) {
      throw StateError(
        'Each domain must have exactly 15 questions '
        '(AUT=${aut.length}, ADHD=${adhd.length}, BEH=${beh.length}).',
      );
    }
    return NeuroQuestionSet(autism: aut, adhd: adhd, behavior: beh);
  }

  static final List<_Band> _bands = [
    _Band(
      0,
      3,
      _set(
        aut: [
          q('Does your baby look at your face while feeding?'),
          q('Does your baby make eye contact when you talk?'),
          q('Does your baby smile in response to your smile?'),
          q('Does your baby respond to your voice?'),
          q('Does your baby calm when you speak softly?'),
          q('Does your baby show interest in people nearby?'),
          q('Does your baby make cooing sounds?'),
          q('Does your baby respond differently to familiar voices?'),
          q('Does your baby enjoy being held?'),
          q('Does your baby try to focus on your face?'),
          q('Does your baby show excitement when you approach?'),
          q('Does your baby react to facial expressions?'),
          q('Does your baby appear aware of surroundings?'),
          q('Does your baby respond to gentle play?'),
          q('Does your baby show early social engagement?'),
        ],
        adhd: [
          q('Can your baby focus on your face for a few seconds?'),
          q('Does your baby follow a moving object with their eyes?'),
          q('Does your baby stay calm during feeding?'),
          q('Does your baby settle after mild discomfort?'),
          q('Does your baby react appropriately to sounds?'),
          q('Does your baby remain alert during awake periods?'),
          q('Does your baby maintain brief attention on toys?'),
          q('Does your baby respond to soothing?'),
          q('Does your baby show regular sleep patterns?'),
          q('Does your baby tolerate short waiting periods?'),
          q('Does your baby respond consistently to stimulation?'),
          q('Does your baby adjust to routine handling?'),
          q('Does your baby remain calm in familiar settings?'),
          q('Does your baby show controlled body movements?'),
          q('Does your baby gradually improve focus over time?'),
        ],
        beh: [
          q('Does your baby calm down when held?'),
          q('Does your baby respond positively to gentle touch?'),
          q('Does your baby express needs clearly through crying?'),
          q('Does your baby relax after feeding?'),
          q('Does your baby appear comfortable most of the day?'),
          q('Does your baby show different facial expressions?'),
          q('Does your baby respond to comforting?'),
          q('Does your baby settle within a reasonable time?'),
          q('Does your baby show pleasure during interaction?'),
          q('Does your baby respond to soothing sounds?'),
          q('Does your baby show predictable reactions?'),
          q('Does your baby seem secure with caregivers?'),
          q('Does your baby enjoy soft play or singing?'),
          q('Does your baby regulate crying with support?'),
          q('Does your baby appear emotionally connected to caregivers?'),
        ],
      ),
    ),
    _Band(
      4,
      6,
      _set(
        aut: [
          q('Does your baby smile spontaneously at people?'),
          q('Does your baby make eye contact during interaction?'),
          q('Does your baby respond when you call their name?'),
          q('Does your baby enjoy face-to-face play?'),
          q('Does your baby show excitement when you approach?'),
          q('Does your baby make different sounds (cooing, babbling)?'),
          q('Does your baby respond to your facial expressions?'),
          q('Does your baby try to imitate sounds?'),
          q('Does your baby turn toward familiar voices?'),
          q('Does your baby show interest in people more than objects?'),
          q('Does your baby laugh during play?'),
          q('Does your baby express pleasure during interaction?'),
          q('Does your baby look at you when upset?'),
          q('Does your baby seek attention through sounds or movement?'),
          q('Does your baby engage in back-and-forth vocal sounds?'),
        ],
        adhd: [
          q('Can your baby focus on a toy for a short time?'),
          q('Does your baby follow moving objects smoothly?'),
          q('Does your baby stay calm during feeding?'),
          q('Does your baby settle when comforted?'),
          q('Does your baby tolerate short waiting periods?'),
          q('Does your baby remain alert during awake times?'),
          q('Does your baby show improving attention over time?'),
          q('Does your baby respond consistently to sounds?'),
          q('Does your baby adjust well to daily routines?'),
          q('Does your baby sleep for expected durations?'),
          q('Does your baby calm down after mild distress?'),
          q('Does your baby avoid excessive irritability?'),
          q('Does your baby respond positively to soothing?'),
          q('Does your baby control body movements better than before?'),
          q('Does your baby show predictable responses to stimulation?'),
        ],
        beh: [
          q('Does your baby calm quickly when held?'),
          q('Does your baby show different emotions (happy, upset)?'),
          q('Does your baby respond warmly to caregivers?'),
          q('Does your baby enjoy social play?'),
          q('Does your baby show attachment to familiar people?'),
          q('Does your baby recover quickly after crying?'),
          q('Does your baby appear content most of the day?'),
          q('Does your baby respond positively to gentle touch?'),
          q('Does your baby express needs clearly?'),
          q('Does your baby appear secure in familiar environments?'),
          q('Does your baby relax during soothing activities?'),
          q('Does your baby respond to singing or talking?'),
          q('Does your baby show comfort during feeding?'),
          q('Does your baby demonstrate consistent sleep routines?'),
          q('Does your baby show pleasure in interaction?'),
        ],
      ),
    ),
    _Band(
      7,
      9,
      _set(
        aut: [
          q('Does your baby respond when their name is called?'),
          q('Does your baby maintain eye contact during play?'),
          q('Does your baby enjoy social games like peek-a-boo?'),
          q('Does your baby smile when interacting with others?'),
          q('Does your baby show different facial expressions?'),
          q('Does your baby babble (ba, ma, da sounds)?'),
          q('Does your baby try to imitate sounds?'),
          q('Does your baby reach out to be picked up?'),
          q('Does your baby show interest in people nearby?'),
          q('Does your baby look at you when you talk?'),
          q('Does your baby respond to your tone of voice?'),
          q('Does your baby express excitement during interaction?'),
          q('Does your baby share attention by looking between you and a toy?'),
          q('Does your baby respond to simple gestures?'),
          q('Does your baby engage in back-and-forth sounds?'),
        ],
        adhd: [
          q('Can your baby focus on a toy for several seconds?'),
          q('Does your baby track moving objects smoothly?'),
          q('Does your baby stay engaged during short play sessions?'),
          q('Does your baby respond appropriately to sounds?'),
          q('Does your baby calm down when comforted?'),
          q('Does your baby tolerate small changes in routine?'),
          q('Does your baby remain alert during wake time?'),
          q('Does your baby avoid excessive fussiness?'),
          q('Does your baby show controlled body movements?'),
          q('Does your baby respond consistently to stimulation?'),
          q('Does your baby sit with support calmly?'),
          q('Does your baby adjust to feeding routines?'),
          q('Does your baby recover quickly after mild frustration?'),
          q('Does your baby show increasing attention span?'),
          q('Does your baby respond positively to structured play?'),
        ],
        beh: [
          q('Does your baby calm easily when upset?'),
          q('Does your baby show attachment to caregivers?'),
          q('Does your baby express emotions clearly?'),
          q('Does your baby respond warmly to familiar people?'),
          q('Does your baby enjoy interactive play?'),
          q('Does your baby appear content most of the time?'),
          q('Does your baby seek comfort when distressed?'),
          q('Does your baby respond to soothing words?'),
          q('Does your baby show excitement during play?'),
          q('Does your baby appear secure in familiar settings?'),
          q('Does your baby express pleasure during feeding?'),
          q('Does your baby show predictable reactions?'),
          q('Does your baby respond positively to gentle touch?'),
          q('Does your baby demonstrate improving emotional control?'),
          q('Does your baby engage socially with caregivers?'),
        ],
      ),
    ),
    _Band(
      10,
      12,
      _set(
        aut: [
          q('Does your baby respond consistently when their name is called?'),
          q('Does your baby use gestures like waving or reaching?'),
          q('Does your baby point toward objects of interest?'),
          q('Does your baby maintain eye contact during interaction?'),
          q('Does your baby enjoy social games like peek-a-boo?'),
          q('Does your baby babble with varied sounds?'),
          q('Does your baby try to copy sounds or gestures?'),
          q('Does your baby look at you to share excitement?'),
          q('Does your baby understand simple words like "no"?'),
          q('Does your baby bring objects to show you?'),
          q('Does your baby show different facial expressions?'),
          q('Does your baby respond to familiar voices?'),
          q('Does your baby engage in back-and-forth interaction?'),
          q('Does your baby show interest in other children?'),
          q('Does your baby seek your attention during play?'),
        ],
        adhd: [
          q('Can your baby focus on a toy for a short time?'),
          q('Does your baby stay engaged during play?'),
          q('Does your baby respond when you call their name?'),
          q('Does your baby follow simple routines?'),
          q('Does your baby calm down when comforted?'),
          q('Does your baby tolerate short waiting periods?'),
          q('Does your baby show improving attention span?'),
          q('Does your baby avoid excessive restlessness?'),
          q('Does your baby respond appropriately to sounds?'),
          q('Does your baby remain calm during feeding?'),
          q('Does your baby shift attention between objects and people?'),
          q('Does your baby recover quickly after mild frustration?'),
          q('Does your baby sit steadily for short periods?'),
          q('Does your baby show controlled body movements?'),
          q('Does your baby respond consistently to familiar cues?'),
        ],
        beh: [
          q('Does your baby calm easily when upset?'),
          q('Does your baby seek comfort from caregivers?'),
          q('Does your baby express emotions clearly?'),
          q('Does your baby show attachment to familiar adults?'),
          q('Does your baby enjoy interactive play?'),
          q('Does your baby respond positively to soothing?'),
          q('Does your baby appear content most of the time?'),
          q('Does your baby show excitement during play?'),
          q('Does your baby adapt to daily routines?'),
          q('Does your baby show predictable sleep patterns?'),
          q('Does your baby engage socially during feeding?'),
          q('Does your baby recover quickly after distress?'),
          q('Does your baby express pleasure when praised?'),
          q('Does your baby appear secure in familiar settings?'),
          q('Does your baby show appropriate emotional reactions?'),
        ],
      ),
    ),
    _Band(
      13,
      15,
      _set(
        aut: [
          q('Does your child respond when their name is called?'),
          q('Does your child point to show interest in something?'),
          q('Does your child use simple gestures like waving bye?'),
          q('Does your child make eye contact during interaction?'),
          q('Does your child say one or two meaningful words?'),
          q('Does your child try to imitate words or sounds?'),
          q('Does your child bring objects to show you?'),
          q('Does your child look at you to share enjoyment?'),
          q('Does your child understand simple instructions?'),
          q('Does your child engage in simple pretend play?'),
          q('Does your child show different facial expressions?'),
          q('Does your child seek your attention during play?'),
          q('Does your child respond to simple questions?'),
          q('Does your child show interest in other children?'),
          q('Does your child enjoy back-and-forth interaction?'),
        ],
        adhd: [
          q('Can your child focus on a toy for at least a minute?'),
          q('Does your child follow simple one-step instructions?'),
          q('Does your child remain seated briefly during activities?'),
          q('Does your child stay engaged in short play sessions?'),
          q('Does your child respond when spoken to directly?'),
          q('Does your child wait briefly when told to pause?'),
          q('Does your child transition calmly between activities?'),
          q('Does your child show improving attention span?'),
          q('Does your child avoid excessive impulsive grabbing?'),
          q('Does your child calm down when comforted?'),
          q('Does your child tolerate short waiting periods?'),
          q('Does your child complete simple tasks?'),
          q('Does your child show controlled body movements?'),
          q('Does your child adapt to daily routines?'),
          q('Does your child recover quickly after frustration?'),
        ],
        beh: [
          q('Does your child calm easily when upset?'),
          q('Does your child seek comfort from caregivers?'),
          q('Does your child show affection toward familiar people?'),
          q('Does your child express emotions clearly?'),
          q('Does your child respond positively to praise?'),
          q('Does your child cooperate during dressing or feeding?'),
          q('Does your child adapt to simple household routines?'),
          q('Does your child play without frequent tantrums?'),
          q('Does your child recover quickly after mild frustration?'),
          q('Does your child respond well to gentle correction?'),
          q('Does your child show appropriate reactions to new situations?'),
          q('Does your child enjoy social interaction?'),
          q('Does your child demonstrate secure attachment?'),
          q('Does your child follow simple boundaries?'),
          q('Does your child express needs using gestures or words?'),
        ],
      ),
    ),
    _Band(
      16,
      18,
      _set(
        aut: [
          q('Does your child respond consistently when their name is called?'),
          q('Does your child point to request or show something?'),
          q('Does your child use at least 3-5 meaningful words?'),
          q('Does your child make eye contact during interaction?'),
          q('Does your child imitate actions like clapping or waving?'),
          q('Does your child bring objects to share with you?'),
          q('Does your child follow simple one-step instructions?'),
          q('Does your child engage in simple pretend play?'),
          q('Does your child look at you to share excitement?'),
          q('Does your child show interest in other children?'),
          q('Does your child enjoy back-and-forth interaction?'),
          q('Does your child use gestures along with sounds?'),
          q('Does your child express different emotions clearly?'),
          q('Does your child seek attention appropriately?'),
          q('Does your child respond to simple social games?'),
        ],
        adhd: [
          q('Can your child focus on an activity for 1-2 minutes?'),
          q('Does your child follow simple instructions?'),
          q('Does your child remain seated briefly during activities?'),
          q('Does your child wait a short moment when asked?'),
          q('Does your child transition between activities calmly?'),
          q('Does your child complete simple tasks?'),
          q('Does your child respond when spoken to directly?'),
          q('Does your child show improving attention span?'),
          q('Does your child avoid excessive impulsive grabbing?'),
          q('Does your child calm down when comforted?'),
          q('Does your child tolerate brief delays?'),
          q('Does your child adapt to daily routines?'),
          q('Does your child play with a toy without quickly losing interest?'),
          q('Does your child show controlled body movements?'),
          q('Does your child recover quickly after frustration?'),
        ],
        beh: [
          q('Does your child calm easily after becoming upset?'),
          q('Does your child seek comfort from caregivers?'),
          q('Does your child show affection toward familiar people?'),
          q('Does your child cooperate during feeding or dressing?'),
          q('Does your child respond positively to praise?'),
          q('Does your child express needs clearly?'),
          q('Does your child adapt to simple routines?'),
          q('Does your child play without frequent intense tantrums?'),
          q('Does your child recover quickly after disappointment?'),
          q('Does your child respond to gentle correction?'),
          q('Does your child show appropriate reactions to strangers?'),
          q('Does your child enjoy social interaction?'),
          q('Does your child demonstrate secure attachment?'),
          q('Does your child follow simple boundaries?'),
          q('Does your child show increasing independence appropriately?'),
        ],
      ),
    ),
    _Band(
      19,
      21,
      _set(
        aut: [
          q('Does your child respond immediately when their name is called?'),
          q('Does your child use at least 10 meaningful words?'),
          q('Does your child point to show or request objects?'),
          q('Does your child make good eye contact during interaction?'),
          q('Does your child follow simple one-step instructions?'),
          q('Does your child imitate household activities?'),
          q('Does your child engage in simple pretend play?'),
          q('Does your child bring objects to share with you?'),
          q('Does your child look at you to share enjoyment?'),
          q('Does your child show interest in other children?'),
          q('Does your child use gestures along with words?'),
          q('Does your child enjoy back-and-forth play?'),
          q('Does your child express different emotions clearly?'),
          q('Does your child respond appropriately to social cues?'),
          q('Does your child seek your attention appropriately?'),
        ],
        adhd: [
          q('Can your child focus on one activity for 2-3 minutes?'),
          q('Does your child follow simple instructions without repeated reminders?'),
          q('Does your child remain seated briefly during meals?'),
          q('Does your child wait a short moment when asked?'),
          q('Does your child transition calmly between activities?'),
          q('Does your child complete simple play tasks?'),
          q('Does your child respond when spoken to directly?'),
          q('Does your child show improving attention span?'),
          q('Does your child avoid frequent impulsive grabbing?'),
          q('Does your child calm down when comforted?'),
          q('Does your child tolerate brief delays without distress?'),
          q('Does your child adapt well to daily routines?'),
          q('Does your child play with toys without constant switching?'),
          q('Does your child show controlled body movements?'),
          q('Does your child recover quickly after mild frustration?'),
        ],
        beh: [
          q('Does your child calm down easily after becoming upset?'),
          q('Does your child seek comfort appropriately from caregivers?'),
          q('Does your child show affection toward familiar people?'),
          q('Does your child cooperate during daily routines?'),
          q('Does your child respond positively to praise?'),
          q('Does your child express emotions using words or gestures?'),
          q('Does your child adapt to simple household rules?'),
          q('Does your child play without frequent intense tantrums?'),
          q('Does your child recover quickly after disappointment?'),
          q('Does your child respond well to gentle correction?'),
          q('Does your child show appropriate reactions to new situations?'),
          q('Does your child enjoy interactive play?'),
          q('Does your child demonstrate secure attachment?'),
          q('Does your child share toys occasionally?'),
          q('Does your child show growing independence appropriately?'),
        ],
      ),
    ),
    _Band(
      22,
      24,
      _set(
        aut: [
          q('Does your child use at least 20 meaningful words?'),
          q('Does your child combine two words (e.g., "more milk")?'),
          q('Does your child respond consistently to their name?'),
          q('Does your child point to show interest in something?'),
          q('Does your child follow simple two-step instructions?'),
          q('Does your child make good eye contact during conversation?'),
          q('Does your child engage in pretend play (feeding doll, talking on phone)?'),
          q('Does your child bring objects to share experiences with you?'),
          q('Does your child look at you to share excitement?'),
          q('Does your child show interest in playing near other children?'),
          q('Does your child imitate actions of adults?'),
          q('Does your child use gestures along with words?'),
          q('Does your child respond appropriately to social cues?'),
          q('Does your child enjoy back-and-forth interaction?'),
          q('Does your child express a variety of emotions clearly?'),
        ],
        adhd: [
          q('Can your child focus on a single activity for 3-5 minutes?'),
          q('Does your child complete simple play tasks?'),
          q('Does your child follow two-step instructions?'),
          q('Does your child remain seated briefly during meals?'),
          q('Does your child wait a short moment when asked?'),
          q('Does your child transition between activities calmly?'),
          q('Does your child respond when spoken to directly?'),
          q('Does your child avoid frequent impulsive actions?'),
          q('Does your child calm down with minimal assistance?'),
          q('Does your child tolerate short waiting periods?'),
          q('Does your child show improving attention span?'),
          q('Does your child play with one toy without constant switching?'),
          q('Does your child adapt to daily routines?'),
          q('Does your child recover quickly after frustration?'),
          q('Does your child control body movements appropriately?'),
        ],
        beh: [
          q('Does your child calm down after being upset within a reasonable time?'),
          q('Does your child seek comfort appropriately?'),
          q('Does your child show affection toward familiar people?'),
          q('Does your child cooperate during daily routines?'),
          q('Does your child respond positively to praise?'),
          q('Does your child express emotions using words or gestures?'),
          q('Does your child adapt to simple household rules?'),
          q('Does your child share toys occasionally?'),
          q('Does your child play without frequent intense tantrums?'),
          q('Does your child recover quickly after disappointment?'),
          q('Does your child respond well to gentle correction?'),
          q('Does your child show appropriate reactions to strangers?'),
          q('Does your child enjoy interacting with other children?'),
          q('Does your child demonstrate secure attachment?'),
          q('Does your child show increasing independence appropriately?'),
        ],
      ),
    ),
    _Band(
      25,
      27,
      _set(
        aut: [
          q('Does your child use two-word phrases regularly?'),
          q('Does your child respond immediately when their name is called?'),
          q('Does your child make good eye contact during conversation?'),
          q('Does your child point to show interest in objects?'),
          q('Does your child follow simple two-step instructions?'),
          q('Does your child engage in pretend play (feeding doll, driving toy car)?'),
          q('Does your child bring objects to share experiences?'),
          q('Does your child look at you to share enjoyment?'),
          q('Does your child show interest in playing near other children?'),
          q('Does your child imitate adult activities?'),
          q('Does your child use gestures along with speech?'),
          q('Does your child respond appropriately to facial expressions?'),
          q('Does your child enjoy back-and-forth conversation attempts?'),
          q('Does your child express a range of emotions clearly?'),
          q('Does your child seek your attention appropriately?'),
        ],
        adhd: [
          q('Can your child focus on one activity for 5 minutes?'),
          q('Does your child complete simple play tasks?'),
          q('Does your child follow instructions without repeated reminders?'),
          q('Does your child remain seated during meals for a short period?'),
          q('Does your child wait briefly when asked?'),
          q('Does your child transition calmly between activities?'),
          q('Does your child respond when spoken to directly?'),
          q('Does your child avoid frequent impulsive grabbing?'),
          q('Does your child tolerate short waiting times?'),
          q('Does your child calm down with minimal support?'),
          q('Does your child stay engaged with a toy without constant switching?'),
          q('Does your child adapt well to daily routines?'),
          q('Does your child recover quickly after frustration?'),
          q('Does your child show improving self-control?'),
          q('Does your child listen when given simple directions?'),
        ],
        beh: [
          q('Does your child calm down within a reasonable time after being upset?'),
          q('Does your child seek comfort appropriately?'),
          q('Does your child show affection toward familiar people?'),
          q('Does your child cooperate during daily routines?'),
          q('Does your child respond positively to praise?'),
          q('Does your child express feelings using words?'),
          q('Does your child adapt to simple rules?'),
          q('Does your child share toys occasionally?'),
          q('Does your child play without frequent intense tantrums?'),
          q('Does your child recover quickly after disappointment?'),
          q('Does your child respond well to gentle correction?'),
          q('Does your child show appropriate reactions to new situations?'),
          q('Does your child enjoy interactive play?'),
          q('Does your child demonstrate secure attachment?'),
          q('Does your child show growing independence appropriately?'),
        ],
      ),
    ),
    _Band(
      28,
      30,
      _set(
        aut: [
          q('Does your child use two- to three-word sentences?'),
          q('Does your child respond consistently to their name?'),
          q('Does your child make eye contact during conversations?'),
          q('Does your child point to show or request things?'),
          q('Does your child follow two-step instructions?'),
          q('Does your child engage in pretend play with imagination?'),
          q('Does your child bring objects to share experiences?'),
          q('Does your child look at you to share enjoyment?'),
          q('Does your child show interest in playing with other children?'),
          q('Does your child imitate adult activities?'),
          q('Does your child use gestures naturally while speaking?'),
          q('Does your child respond appropriately to social cues?'),
          q('Does your child enjoy simple back-and-forth conversations?'),
          q('Does your child express a variety of emotions clearly?'),
          q('Does your child seek attention in appropriate ways?'),
        ],
        adhd: [
          q('Can your child focus on an activity for 5-7 minutes?'),
          q('Does your child complete simple tasks without constant reminders?'),
          q('Does your child follow instructions carefully?'),
          q('Does your child remain seated briefly during meals or activities?'),
          q('Does your child wait for a short time when asked?'),
          q('Does your child transition calmly between activities?'),
          q('Does your child respond when spoken to directly?'),
          q('Does your child avoid frequent impulsive actions?'),
          q('Does your child tolerate short waiting periods?'),
          q('Does your child calm down with minimal assistance?'),
          q('Does your child stay engaged with one toy for some time?'),
          q('Does your child adapt to daily routines?'),
          q('Does your child recover quickly after frustration?'),
          q('Does your child show improving self-control?'),
          q('Does your child listen and respond to directions?'),
        ],
        beh: [
          q('Does your child calm down within a reasonable time after being upset?'),
          q('Does your child seek comfort appropriately?'),
          q('Does your child show affection toward family members?'),
          q('Does your child cooperate during daily routines?'),
          q('Does your child respond positively to praise?'),
          q('Does your child express feelings using simple sentences?'),
          q('Does your child adapt to simple household rules?'),
          q('Does your child share toys occasionally?'),
          q('Does your child play without frequent intense tantrums?'),
          q('Does your child recover quickly after disappointment?'),
          q('Does your child respond well to gentle correction?'),
          q('Does your child show appropriate reactions to new situations?'),
          q('Does your child enjoy interactive play?'),
          q('Does your child demonstrate secure attachment?'),
          q('Does your child show growing independence appropriately?'),
        ],
      ),
    ),
    _Band(
      31,
      33,
      _set(
        aut: [
          q('Does your child speak in short sentences of 3 or more words?'),
          q('Does your child respond consistently when called by name?'),
          q('Does your child make good eye contact during conversation?'),
          q('Does your child point to show or request things?'),
          q('Does your child follow two-step instructions?'),
          q('Does your child engage in pretend play with imagination?'),
          q('Does your child bring objects to share experiences?'),
          q('Does your child look at you to share enjoyment?'),
          q('Does your child show interest in playing with other children?'),
          q('Does your child imitate adult activities appropriately?'),
          q('Does your child use gestures naturally while speaking?'),
          q('Does your child respond appropriately to facial expressions?'),
          q('Does your child enjoy back-and-forth conversations?'),
          q('Does your child express different emotions clearly?'),
          q('Does your child seek attention in appropriate ways?'),
        ],
        adhd: [
          q('Can your child focus on an activity for 7-10 minutes?'),
          q('Does your child complete simple tasks independently?'),
          q('Does your child follow instructions without repeated reminders?'),
          q('Does your child remain seated during meals for a reasonable time?'),
          q('Does your child wait briefly when asked?'),
          q('Does your child transition calmly between activities?'),
          q('Does your child respond when spoken to directly?'),
          q('Does your child avoid frequent impulsive behavior?'),
          q('Does your child tolerate short waiting periods?'),
          q('Does your child calm down with minimal assistance?'),
          q('Does your child stay engaged with one toy for several minutes?'),
          q('Does your child adapt well to daily routines?'),
          q('Does your child recover quickly after frustration?'),
          q('Does your child show improving self-control?'),
          q('Does your child listen carefully to directions?'),
        ],
        beh: [
          q('Does your child calm down within a reasonable time after being upset?'),
          q('Does your child seek comfort appropriately?'),
          q('Does your child show affection toward familiar people?'),
          q('Does your child cooperate during daily routines?'),
          q('Does your child respond positively to praise?'),
          q('Does your child express feelings using simple sentences?'),
          q('Does your child adapt to household rules?'),
          q('Does your child share toys occasionally?'),
          q('Does your child play without frequent intense tantrums?'),
          q('Does your child recover quickly after disappointment?'),
          q('Does your child respond well to gentle correction?'),
          q('Does your child show appropriate reactions to new situations?'),
          q('Does your child enjoy interactive group play?'),
          q('Does your child demonstrate secure attachment?'),
          q('Does your child show age-appropriate independence?'),
        ],
      ),
    ),
    _Band(
      34,
      36,
      _set(
        aut: [
          q('Does your child speak in clear 3-4 word sentences?'),
          q('Does your child respond consistently when called by name?'),
          q('Does your child maintain eye contact during conversation?'),
          q('Does your child engage in imaginative pretend play?'),
          q('Does your child follow two- to three-step instructions?'),
          q('Does your child ask simple questions?'),
          q('Does your child share interests by showing or telling you things?'),
          q('Does your child enjoy playing with other children?'),
          q('Does your child take turns during play?'),
          q('Does your child use gestures naturally while speaking?'),
          q('Does your child understand simple emotions in others?'),
          q('Does your child respond appropriately to social cues?'),
          q('Does your child participate in back-and-forth conversations?'),
          q('Does your child show a variety of facial expressions?'),
          q('Does your child seek attention in appropriate social ways?'),
        ],
        adhd: [
          q('Can your child focus on an activity for 10 minutes?'),
          q('Does your child complete simple tasks independently?'),
          q('Does your child follow instructions without repeated reminders?'),
          q('Does your child remain seated during meals appropriately?'),
          q('Does your child wait briefly for their turn?'),
          q('Does your child transition calmly between activities?'),
          q('Does your child listen when spoken to directly?'),
          q('Does your child avoid frequent impulsive behavior?'),
          q('Does your child control body movements appropriately?'),
          q('Does your child tolerate short waiting periods?'),
          q('Does your child stay engaged in structured activities?'),
          q('Does your child adapt well to daily routines?'),
          q('Does your child recover quickly after frustration?'),
          q('Does your child show improving self-control?'),
          q('Does your child respond positively to structured guidance?'),
        ],
        beh: [
          q('Does your child calm down within a reasonable time after being upset?'),
          q('Does your child seek comfort appropriately?'),
          q('Does your child show affection toward family members?'),
          q('Does your child cooperate during daily routines?'),
          q('Does your child respond positively to praise?'),
          q('Does your child express feelings using sentences?'),
          q('Does your child adapt to household rules?'),
          q('Does your child share toys willingly?'),
          q('Does your child play without frequent intense tantrums?'),
          q('Does your child recover quickly after disappointment?'),
          q('Does your child respond well to gentle correction?'),
          q('Does your child show appropriate reactions to new situations?'),
          q('Does your child enjoy group play?'),
          q('Does your child demonstrate empathy toward others?'),
          q('Does your child show age-appropriate independence?'),
        ],
      ),
    ),
    _Band(
      37,
      48,
      _set(
        aut: [
          q('Does your child speak in clear, complete sentences?'),
          q('Does your child maintain eye contact during conversations?'),
          q('Does your child engage in imaginative pretend play?'),
          q('Does your child understand simple jokes or humor?'),
          q('Does your child follow three-step instructions?'),
          q('Does your child ask and answer simple questions?'),
          q('Does your child show interest in playing cooperatively with peers?'),
          q('Does your child take turns during games?'),
          q('Does your child express emotions clearly?'),
          q('Does your child understand others\' emotions?'),
          q('Does your child participate in back-and-forth conversations?'),
          q('Does your child use gestures appropriately while speaking?'),
          q('Does your child adjust behavior in different social settings?'),
          q('Does your child share experiences verbally?'),
          q('Does your child seek attention in socially appropriate ways?'),
        ],
        adhd: [
          q('Can your child focus on a task for 10-15 minutes?'),
          q('Does your child complete tasks without frequent reminders?'),
          q('Does your child follow instructions carefully?'),
          q('Does your child wait for their turn during play?'),
          q('Does your child remain seated during meals or class activities?'),
          q('Does your child listen when spoken to directly?'),
          q('Does your child avoid interrupting others frequently?'),
          q('Does your child control impulsive behavior?'),
          q('Does your child organize simple play activities?'),
          q('Does your child stay engaged in structured group activities?'),
          q('Does your child adapt calmly to changes in routine?'),
          q('Does your child finish activities they start?'),
          q('Does your child show age-appropriate patience?'),
          q('Does your child respond positively to correction?'),
          q('Does your child demonstrate improving self-control?'),
        ],
        beh: [
          q('Does your child calm down after being upset within a reasonable time?'),
          q('Does your child express feelings using appropriate words?'),
          q('Does your child cooperate with adults?'),
          q('Does your child follow household or classroom rules?'),
          q('Does your child share toys willingly?'),
          q('Does your child play cooperatively with peers?'),
          q('Does your child handle small disappointments appropriately?'),
          q('Does your child respond positively to praise?'),
          q('Does your child demonstrate empathy toward others?'),
          q('Does your child avoid frequent aggressive behavior?'),
          q('Does your child recover quickly after frustration?'),
          q('Does your child adapt well to new environments?'),
          q('Does your child accept guidance calmly?'),
          q('Does your child demonstrate respect toward adults?'),
          q('Does your child show age-appropriate independence?'),
        ],
      ),
    ),
    _Band(
      49,
      60,
      _set(
        aut: [
          q('Does your child speak clearly in full sentences?'),
          q('Does your child maintain appropriate eye contact during conversation?'),
          q('Does your child understand and respond to others\' emotions?'),
          q('Does your child engage in imaginative group play?'),
          q('Does your child follow multi-step instructions?'),
          q('Does your child ask meaningful questions?'),
          q('Does your child participate in back-and-forth conversations?'),
          q('Does your child adjust tone of voice appropriately?'),
          q('Does your child show interest in friendships?'),
          q('Does your child take turns during structured games?'),
          q('Does your child understand simple social rules?'),
          q('Does your child use gestures naturally while speaking?'),
          q('Does your child share experiences or stories?'),
          q('Does your child respond appropriately in social situations?'),
          q('Does your child adapt to changes in routine with minimal distress?'),
        ],
        adhd: [
          q('Can your child focus on an activity for 15-20 minutes?'),
          q('Does your child complete assigned tasks independently?'),
          q('Does your child follow instructions without repeated reminders?'),
          q('Does your child remain seated during structured activities?'),
          q('Does your child wait for their turn appropriately?'),
          q('Does your child listen carefully when spoken to?'),
          q('Does your child avoid interrupting conversations?'),
          q('Does your child control impulsive behavior?'),
          q('Does your child stay organized during play or school tasks?'),
          q('Does your child finish tasks before moving to new ones?'),
          q('Does your child transition calmly between activities?'),
          q('Does your child manage small frustrations appropriately?'),
          q('Does your child demonstrate patience in group settings?'),
          q('Does your child respond positively to correction?'),
          q('Does your child show consistent self-control across settings?'),
        ],
        beh: [
          q('Does your child express feelings using appropriate words?'),
          q('Does your child cooperate with teachers or adults?'),
          q('Does your child follow classroom or household rules?'),
          q('Does your child play cooperatively with peers?'),
          q('Does your child resolve small conflicts calmly?'),
          q('Does your child demonstrate empathy toward others?'),
          q('Does your child avoid frequent aggressive behavior?'),
          q('Does your child handle disappointment appropriately?'),
          q('Does your child respond positively to praise?'),
          q('Does your child recover quickly after emotional upset?'),
          q('Does your child adapt well to new environments?'),
          q('Does your child accept guidance calmly?'),
          q('Does your child demonstrate respect toward others?'),
          q('Does your child show age-appropriate independence?'),
          q('Does your child maintain positive peer relationships?'),
        ],
      ),
    ),
    _Band(
      61,
      72,
      _set(
        aut: [
          q('Does your child speak clearly in full, meaningful sentences?'),
          q('Does your child maintain appropriate eye contact during conversation?'),
          q('Does your child understand and respond to others\' emotions?'),
          q('Does your child participate in cooperative group play?'),
          q('Does your child follow multi-step instructions independently?'),
          q('Does your child engage in imaginative and creative play?'),
          q('Does your child maintain back-and-forth conversations?'),
          q('Does your child understand simple humor or sarcasm?'),
          q('Does your child adjust behavior based on social setting?'),
          q('Does your child share personal experiences or stories clearly?'),
          q('Does your child form friendships with peers?'),
          q('Does your child respect personal space of others?'),
          q('Does your child respond appropriately to social feedback?'),
          q('Does your child adapt to small changes in routine calmly?'),
          q('Does your child seek help appropriately when needed?'),
        ],
        adhd: [
          q('Can your child focus on structured tasks for 20 minutes?'),
          q('Does your child complete homework or assigned tasks independently?'),
          q('Does your child follow instructions without repeated reminders?'),
          q('Does your child remain seated during class activities?'),
          q('Does your child wait patiently for their turn?'),
          q('Does your child listen carefully when spoken to?'),
          q('Does your child avoid interrupting others?'),
          q('Does your child organize school materials properly?'),
          q('Does your child finish tasks before starting new ones?'),
          q('Does your child transition calmly between activities?'),
          q('Does your child manage frustration appropriately?'),
          q('Does your child demonstrate patience in group settings?'),
          q('Does your child control impulsive actions?'),
          q('Does your child respond positively to correction?'),
          q('Does your child show consistent self-control across environments?'),
        ],
        beh: [
          q('Does your child express feelings appropriately using words?'),
          q('Does your child cooperate with teachers and adults?'),
          q('Does your child follow classroom rules consistently?'),
          q('Does your child resolve conflicts peacefully?'),
          q('Does your child demonstrate empathy toward peers?'),
          q('Does your child avoid aggressive behavior?'),
          q('Does your child handle disappointment calmly?'),
          q('Does your child respond positively to praise?'),
          q('Does your child recover quickly after emotional upset?'),
          q('Does your child adapt well to new environments?'),
          q('Does your child accept guidance respectfully?'),
          q('Does your child show responsibility for small tasks?'),
          q('Does your child maintain healthy peer relationships?'),
          q('Does your child demonstrate age-appropriate independence?'),
          q('Does your child show emotional stability in daily routines?'),
        ],
      ),
    ),
  ];
}
