# Generated by Django 6.0.1 on 2026-02-17 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('GM', 'Gross Motor'), ('FM', 'Fine Motor'), ('LC', 'Language & Communication'), ('COG', 'Cognitive'), ('SE', 'Socio-Emotional')], max_length=4)),
                ('age_band', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('weight', models.IntegerField(default=2)),
                ('is_red_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('age_months', models.IntegerField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.child')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.question')),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.screening')),
            ],
        ),
        migrations.CreateModel(
            name='DomainScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=4)),
                ('probability', models.FloatField()),
                ('risk_label', models.CharField(max_length=20)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenings.screening')),
            ],
        ),
    ]
