# Generated by Codex for Problem C + D scaffolding.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screenings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='awc_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='child',
            name='district_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='child',
            name='mandal_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='child',
            name='sector_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.CreateModel(
            name='FollowupOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_delay_months', models.IntegerField(default=0)),
                ('followup_delay_months', models.IntegerField(default=0)),
                ('improvement_status', models.CharField(choices=[('Improving', 'Improving'), ('Worsening', 'Worsening'), ('No Change', 'No Change')], default='No Change', max_length=20)),
                ('followup_completed', models.BooleanField(default=False)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=models.CASCADE, to='screenings.child')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_required', models.BooleanField(default=False)),
                ('referral_date', models.DateField(blank=True, null=True)),
                ('referral_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Under Treatment', 'Under Treatment')], default='Pending', max_length=30)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=models.CASCADE, to='screenings.child')),
            ],
        ),
        migrations.CreateModel(
            name='WorkforcePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awc_id', models.CharField(max_length=40)),
                ('aww_trained', models.BooleanField(default=False)),
                ('supervisor_trained', models.BooleanField(default=False)),
                ('cdpo_trained', models.BooleanField(default=False)),
                ('training_mode', models.CharField(blank=True, default='', max_length=20)),
                ('parents_sensitized', models.IntegerField(default=0)),
                ('parents_assigned_intervention', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
